### ISSUE TITLE
Eldritch Gown erroring entity

### ISSUE THREAD

**Issue by srnyx** [PheonixVX/fof#9] opened 2021-06-26 15:15 UTC
Whenever the Eldritch Gown tries to attack, a mod I'm using removes it (so that the server doesn't crash): https://paste.srnyx.xyz/weluhebugu.properties

**Comment by PhoenixVX** [comment] 2021-07-01 19:22
Duplicate of issue #8

**Comment by PhoenixVX** [comment] 2021-07-01 19:23
That should be fixed in the latest commit. Try that and report back

**Comment by srnyx** [comment] 2021-07-03 14:13
I've recently shutdown my modded server.
This also means I'm leaving a majority of the Fabric/modded community. Sorry if this causes any complications.

**Closed as completed** 2021-07-03 14:14 UTC
